DELETE http://localhost:3001/api/persons/64bbf77381f10a7e3e0a5da0

###
GET http://localhost:3001/api/persons/

###
PUT http://localhost:3001/api/persons/64bcdbe4e4b441f3ac55a3c2
Content-Type: application/json

{
    "name": "Arthur Moran",
    "number": 999999
}